name: GitHub Actions v1

on:
  # pull_request:
  #   branches: [main, staging]
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-linters:
    name: Run linter
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        # with:
        #   swift-version: "5.6.1"

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Lint Action
        uses: wearerequired/lint-action@v2.0.0
        with:
          auto_fix: true
          swiftlint: true
          swiftlint_auto_fix: true

  build:
    name: Test build
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2.1'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Setup CocoaPods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: Podfile.lock

      - name: Install CocoaPods
        run: pod install

      - name: Bundle install
        run: bundle install
