name: Swift Test

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install CocoaPods
        run: pod install

      # - name: Build
      #   run: xcodebuild -workspace GHAT2.xcworkspace -scheme GHAT2 -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14'
      - name: "Displays Xcode current version"
        run: sudo xcode-select -p
        
      - name: Run tests
        run: xcodebuild -workspace GHAT2.xcworkspace -scheme GHAT2 -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14'" test
